import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {sampleInfo,filterCells,groupCells,summarize,mannWhitney,adjustBH,compareGenes,insidePolygon} from '../research.mjs';
import {drawDistribution,panelSVG} from '../plots.mjs';
const read=id=>JSON.parse(fs.readFileSync(new URL('./fixtures/cohorts/'+id+'.json',import.meta.url)));
const expected={
'GSE178121':['Control','Diabetes'],'E-MTAB-9061':['Diabetes','Control'],'GSE168908':['Control','Diabetes'],'GSE205123':['Control','Diabetes'],'GSE313176':['Control','Diabetes'],'GSE328966':['Control','Control','Diabetes','Diabetes'],'GSE243100':['Control','Control','Diabetes','Diabetes'],'GSE209872':['Control','Diabetes','Diabetes','Diabetes'],'GSE204880':['Control','Control','Diabetes','Diabetes','Control','Diabetes'],'GSE245561':['PDR','PDR','PDR','PDR'],'GSE248284':['Diabetes without DR','Diabetes without DR','Diabetes without DR','Diabetic retinopathy','Diabetic retinopathy','Diabetic retinopathy'],'GSE165784':['PDR','PDR','PVR','PDR','PDR','PDR'],'GSE150703':[...Array(11).fill('Normoxia'),...Array(8).fill('OIR')],'GSE152928':['Control','OIR'],'GSE199792':['Control','OIR'],'GSE319256':['Vldlr knockout','Control'],'GSE175499':[...Array(4).fill('Control'),...Array(23).fill('SFTS')]};
for(const[id,conditions]of Object.entries(expected))test(id+' respects deposited cohorts',()=>assert.deepEqual(sampleInfo(read(id)).map(s=>s.condition),conditions));
const meta={id:'fixture',cells:8,groups:[{id:0,name:'C0 · Rod'},{id:1,name:'C1 · Myeloid'}],samples:['s0','s1','s2','s3']},cells={sample:[0,0,1,1,2,2,3,3],cluster:[0,1,0,1,0,1,0,1]},samples=[{index:0,id:'s0',title:'s0',condition:'Control',tissue:'Retina'},{index:1,id:'s1',title:'s1',condition:'Diabetes',tissue:'Retina'},{index:2,id:'s2',title:'s2',condition:'Control',tissue:'Kidney'},{index:3,id:'s3',title:'s3',condition:'Diabetes',tissue:'Kidney'}];
const filters=()=>({samples:new Set([0,1,2,3]),types:new Set(['Rod','Myeloid']),clusters:new Set([0,1]),tissue:'all',scope:'all'});
test('sample, type, cluster, tissue and cell filters intersect',()=>{let f=filters();f.tissue='Retina';f.types=new Set(['Myeloid']);assert.deepEqual(filterCells(meta,cells,samples,f),[1,3]);f.samples.delete(1);assert.deepEqual(filterCells(meta,cells,samples,f),[1]);f.clusters.delete(1);assert.deepEqual(filterCells(meta,cells,samples,f),[]);});
test('clearing every sample really yields no cells',()=>{const f=filters();f.samples.clear();assert.deepEqual(filterCells(meta,cells,samples,f),[]);});
test('selection and reclustered subset cannot leak unselected cells',()=>{const f=filters();f.scope='selected';assert.deepEqual(filterCells(meta,cells,samples,f,new Set([0,1,2]),new Set([3]),new Set([1,3,7])),[1,3]);});
test('pooling uses recorded conditions with library counts',()=>{const g=groupCells(meta,cells,samples,[0,1,2,3,4,5,6,7],'condition');assert.deepEqual(g.map(x=>[x.name,x.ids,x.samples]),[['Control',[0,1,4,5],[0,2]],['Diabetes',[2,3,6,7],[1,3]]]);});
test('custom groups exclude unassigned sample libraries',()=>{const g=groupCells(meta,cells,samples,[0,1,2,3,4,5,6,7],'custom',{assignment:{0:'a',1:'b',2:'exclude',3:'a'},nameA:'Custom control'});assert.deepEqual(g.map(x=>x.ids),[[0,1,6,7],[2,3]]);});
test('cell type × condition groups do not mix identities',()=>{const g=groupCells(meta,cells,samples,[0,1,2,3],'type-condition');assert.equal(g.length,4);assert.ok(g.every(x=>x.ids.length===1));});
test('distribution quartiles, zeros and observed whiskers',()=>{const s=summarize([0,1,2,3,4,5,6],new Float32Array([0,0,1,2,3,4,50]));assert.equal(s.median,2);assert.equal(s.q1,.5);assert.equal(s.q3,3.5);assert.equal(s.low,0);assert.equal(s.high,4);assert.equal(s.max,50);assert.equal(s.n,7);assert.equal(s.pct,5/7*100);});
test('empty and constant populations are explicit',()=>{assert.equal(summarize([],[]).mean,null);assert.equal(mannWhitney([0,1,2],[3,4,5],new Float32Array(6)),1);assert.equal(mannWhitney([0,1],[3,4,5],new Float32Array(6)),null);assert.throws(()=>mannWhitney([0,1,2],[2,3,4],new Float32Array(5)),/overlap/);});
test('BH correction is across valid selected genes',()=>{const q=adjustBH([.01,.04,.03,null]);assert.deepEqual(q,[.03,.04,.04,null]);});
test('lasso polygon membership handles nonrectangular selections',()=>{assert.equal(insidePolygon(1,1,[[0,0],[5,0],[0,5]]),true);assert.equal(insidePolygon(4,4,[[0,0],[5,0],[0,5]]),false);});
test('every selected cell is drawn, including zero, without sampling',()=>{let dots=0;const ctx=new Proxy({measureText:s=>({width:s.length*6}),fillRect:(x,y,w,h)=>{if(w===2&&h===2)dots++;}},{get:(o,k)=>k in o?o[k]:()=>{},set:(o,k,v)=>(o[k]=v,true)}),canvas={style:{},dataset:{},getContext:()=>ctx};const g=[{name:'Control',ids:[0,1,2]},{name:'Diabetes',ids:[3,4]}],v=new Float32Array([0,0,5,0,1]);drawDistribution(canvas,g,v);assert.equal(dots,5);assert.equal(canvas.dataset.pointsDrawn,'5');drawDistribution(canvas,g,v,{showPoints:false});assert.equal(canvas.dataset.pointsDrawn,'0');assert.equal(canvas.dataset.cellCount,'5');drawDistribution(canvas,[],v);assert.equal(canvas.dataset.cellCount,'0');});
test('dot plot statistics match the chosen cells, including zeros',()=>{const r=panelSVG([{name:'Selected',ids:[0,1]}],[new Float32Array([0,2,99])],['Gene']);assert.equal(r.grid[0][0].mean,1);assert.equal(r.grid[0][0].pct,50);assert.match(r.svg,/Detected cells/);});
test('statistics worker accepts the browser message contract',()=>{const script=fs.readFileSync(new URL('../stats-worker.mjs',import.meta.url),'utf8').replace(/^import[^\n]+\n/,'');let result;const context={compareGenes,self:{postMessage:x=>result=x}};vm.runInNewContext(script,context);context.self.onmessage({data:{id:12,geneNames:['g'],vectors:[new Float32Array([0,1,2,3,4,5])],a:[0,1,2],b:[3,4,5]}});assert.equal(result.id,12);assert.ok(!result.error,result.error);assert.equal(result.rows[0].gene,'g');assert.equal(result.rows[0].nA,3);});
const oracle=JSON.parse(fs.readFileSync(new URL('./fixtures/statistics-oracle.json',import.meta.url)));
for(const row of oracle)test('independent SciPy check: '+row.name,()=>{const result=compareGenes(row.genes,row.vectors.map(v=>new Float32Array(v)),row.a,row.b);result.forEach((r,i)=>{const p=row.expected[i].pvalue;assert.ok(Math.abs(r.pvalue-p)<Math.max(1e-300,p*3e-6),`${r.pvalue} vs ${p}`);assert.ok(Math.abs(r.log2FC-row.expected[i].log2FC)<1e-6);});});

test('saved reclustered subsets can group their new clusters without mixing parent cells',()=>{const subset={lookup:new Map([[1,0],[3,1],[7,2]]),cluster:[0,1,0]};const groups=groupCells(meta,cells,samples,[0,1,3,7],'subset',{},new Set(),new Set(),subset);assert.deepEqual(groups.map(g=>[g.name,g.ids]),[['Reclustered C0',[1,7]],['Reclustered C1',[3]]]);});
