const {gzipSync,gunzipSync}=require('node:zlib');
const {createHash,timingSafeEqual}=require('node:crypto');
const REPO=process.env.GITHUB_REPOSITORY||'TailsOS-hack/retina-spectacle';
const cache=new Map();
async function gh(path,method='GET',data){const r=await fetch(`https://api.github.com/repos/${REPO}/${path}`,{method,headers:{Authorization:`Bearer ${process.env.GH_TOKEN}`,'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',...(data?{'Content-Type':'application/json'}:{})},body:data?JSON.stringify(data):undefined});if(!r.ok){const e=Error(`Repository service returned ${r.status}`);e.status=r.status;throw e}return r.status===204?{}:r.json()}
async function file(path){try{const f=await gh('contents/'+path);return {value:JSON.parse(Buffer.from(f.content,'base64')),sha:f.sha}}catch(e){if(e.status===404)return null;throw e}}
async function save(path,value,sha){return gh('contents/'+path,'PUT',{message:'Update '+path,content:Buffer.from(JSON.stringify(value)).toString('base64'),...(sha?{sha}:{})})}
async function catalog(){const hit=cache.get('catalog');if(hit&&Date.now()-hit.at<20000)return hit.value;const f=await file('state/catalog.json');if(!f)throw Error('Dataset catalog is being initialized');cache.set('catalog',{at:Date.now(),value:f.value});return f.value}
function send(res,obj,status=200,ttl=0){const b=gzipSync(Buffer.from(JSON.stringify(obj)));res.statusCode=status;res.setHeader('Content-Type','application/json');res.setHeader('Content-Encoding','gzip');res.setHeader('Cache-Control',ttl?`public, max-age=${ttl}, s-maxage=${ttl}`:'no-store');res.end(b)}
function auth(req){const a=Buffer.from(String(req.headers['x-admin-key']||'')),b=Buffer.from(process.env.ADMIN_KEY||'');if(!b.length||a.length!==b.length||!timingSafeEqual(a,b)){const e=Error('An analysis access code is required');e.status=401;throw e}}
function checkedStudy(c,acc,revision){if(!/^(GSE\d+|E-MTAB-\d+)$/.test(acc)){const e=Error('Invalid accession');e.status=400;throw e}const row=c.studies.find(r=>r.id===acc);if(!row||row.status!=='ready'){const e=Error('Dataset is not ready');e.status=404;throw e}const rev=revision||row.activeVersion||'legacy';if(!(row.publishedVersions||['legacy']).includes(rev)){const e=Error('Unknown dataset version');e.status=404;throw e}return{row,rev}}
function releaseURL(acc,rev,name){return `https://github.com/${REPO}/releases/download/dataset-${acc.toLowerCase()}-${rev}/${name}`}
async function asset(url,range){const r=await fetch(url,{headers:range?{Range:range}:{}});if(!r.ok){const e=Error('Processed data file is temporarily unavailable');e.status=502;throw e}if(range&&r.status!==206)throw Error('Data repository did not honor the requested byte range');return Buffer.from(await r.arrayBuffer())}
async function index(acc,rev){const key=acc+'/'+rev;let value=cache.get(key);if(!value){value=JSON.parse(gunzipSync(await asset(releaseURL(acc,rev,'matrix-index.json.gz'))));cache.set(key,value);if(cache.size>24){const first=[...cache.keys()].find(k=>k!=='catalog');cache.delete(first)}}return value}
async function dispatch(kind,id='',target=''){return gh('actions/workflows/process.yml/dispatches','POST',{ref:'main',inputs:{kind,job_id:id,target}})}
async function refresh(){
 const c=await catalog(),f=c.freshness||{},now=Date.now()/1000,bucket=Math.floor(now/1800);
 if(now-(f.lastCheckedAt||0)<1800)return {...f,started:false,nextCheckAt:(bucket+1)*1800};
 const lock=await file('control/refresh-lock.json');
 if(lock?.value.bucket===bucket&&lock.value.status!=='failed')return {...f,status:'checking',started:false,nextCheckAt:(bucket+1)*1800};
 let claim;
 try{claim=await save('control/refresh-lock.json',{bucket,startedAt:now,status:'queued'},lock?.sha)}catch(e){if([409,422].includes(e.status))return {...f,status:'checking',started:false};throw e}
 try{await dispatch('refresh')}catch(e){await save('control/refresh-lock.json',{bucket,status:'failed',startedAt:now},claim.content.sha).catch(()=>{});throw e}
 return {...f,status:'checking',started:true,startedAt:now,nextCheckAt:(bucket+1)*1800}
}
module.exports=async(req,res)=>{try{const u=new URL(req.url,'https://app.local');const path=u.pathname.replace(/^\/api\/?/,'').split('/').filter(Boolean);const [first,acc,type,arg]=path;
 if(req.method==='GET'&&first==='health')return send(res,{status:'ok',version:'3.0-free',provider:'GitHub Actions + Vercel',preloadedExpressionData:false});
 if(req.method==='GET'&&first==='studies')return send(res,await catalog(),200,15);
 if(req.method==='POST'&&first==='refresh')return send(res,await refresh());
 if(req.method==='POST'&&(first==='import-review'||first==='retry')){auth(req);if(first==='retry'){const c=await catalog();if(!c.studies.some(r=>r.id===acc))return send(res,{detail:'Unknown source'},400)}await dispatch('refresh','',first==='retry'?acc:'');return send(res,{status:'queued'});}
 if(req.method==='GET'&&first==='data'){const {rev}=checkedStudy(await catalog(),acc,u.searchParams.get('revision'));if(/^(?:meta|cells(?:-\d{3})?|genes(?:-\d{3})?)\.json$/.test(type)){const b=await asset(releaseURL(acc,rev,type+'.gz'));res.setHeader('Content-Type','application/json');res.setHeader('Content-Encoding','gzip');res.setHeader('Cache-Control',u.searchParams.has('revision')?'public,max-age=31536000,immutable':'no-cache');return res.end(b)}if(type==='gene'){const ix=Number(arg),idx=await index(acc,rev);if(!Number.isInteger(ix)||ix<0||ix>=idx.index.length)return send(res,{detail:'Unknown gene'},404);const [part,start,n,compressedLength]=idx.index[ix],length=compressedLength??n*8;let b=n?await asset(releaseURL(acc,rev,`expression-${String(part).padStart(3,'0')}.bin`),`bytes=${start}-${start+length-1}`):Buffer.alloc(0);if(n&&idx.encoding==='gzip-per-gene')b=gunzipSync(b);if(b.length!==n*8)throw Error('Expression byte count mismatch');const indices=[],values=[];for(let i=0;i<n;i++){indices.push(b.readUInt32LE(i*8));values.push(Number(b.readFloatLE(i*8+4).toFixed(5)))}return send(res,{indices,values,cells:idx.cells,gene:idx.genes[ix]},200,u.searchParams.has('revision')?31536000:30)}}
 if(req.method==='POST'&&first==='analysis'){auth(req);const c=await catalog(),payload=typeof req.body==='object'?req.body:JSON.parse(req.body||'{}');const{row,rev}=checkedStudy(c,acc,payload.revision);if(!['differential','recluster'].includes(type))return send(res,{detail:'Unknown analysis'},400);payload.revision=rev;for(const k of type==='differential'?['a','b']:['cells']){const a=payload[k];if(!Array.isArray(a)||!a.length||a.length>250000||a.some(i=>!Number.isInteger(i)||i<0||i>=row.cells))return send(res,{detail:'Invalid cell selection'},400);payload[k]=[...new Set(a)].sort((a,b)=>a-b)}if(type==='differential'){const bSet=new Set(payload.b);if(payload.a.length<3||payload.b.length<3||payload.a.some(x=>bSet.has(x)))return send(res,{detail:'Select disjoint groups with at least three cells each'},400);if(!(Number(payload.minPct)>=0&&Number(payload.minPct)<=1&&Number(payload.logfc)>=0&&Number(payload.logfc)<=20))return send(res,{detail:'Invalid thresholds'},400)}else if(payload.cells.length<12||payload.cells.length>50000)return send(res,{detail:'Reclustering supports 12–50,000 cells'},400);const id=createHash('sha256').update(JSON.stringify([acc,type,payload])).digest('hex').slice(0,24),requestPath='control/jobs/'+id+'.json';let job=await file('state/jobs/'+id+'.json');if(job&&job.value.status!=='failed')return send(res,job.value);const existing=await file(requestPath);const record={id,study:acc,revision:rev,kind:type,status:'queued',message:'Queued on a free research runner',createdAt:Date.now()/1000,payload:gzipSync(Buffer.from(JSON.stringify(payload))).toString('base64')};let claimed=false;
 if(!existing||existing.value.status==='dispatch_failed'||job?.value.status==='failed'){
  try{await save(requestPath,record,existing?.sha);claimed=true}catch(e){if(![409,422].includes(e.status))throw e}
 }
 if(claimed){
  const publicRecord={...record};delete publicRecord.payload;await save('state/jobs/'+id+'.json',publicRecord,job?.sha);
  try{await dispatch('analysis',id)}catch(e){const current=await file(requestPath);await save(requestPath,{...record,status:'dispatch_failed'},current?.sha).catch(()=>{});const state=await file('state/jobs/'+id+'.json');await save('state/jobs/'+id+'.json',{...publicRecord,status:'failed',message:'Could not start the runner. Retry this selection.'},state?.sha).catch(()=>{});throw e}
 }
 delete record.payload;return send(res,record);}
 if(req.method==='GET'&&first==='jobs'){if(!/^[a-f0-9]{24}$/.test(acc))return send(res,{detail:'Invalid job'},400);const result=await file('state/jobs/'+acc+'.json');const job=result?.value||(await file('control/jobs/'+acc+'.json'))?.value;if(!job)return send(res,{detail:'Unknown job'},404);delete job.payload;if(job.status==='ready'){const base=`https://github.com/${REPO}/releases/download/job-${acc}/`;if(type==='xlsx'){const b=await asset(base+'result.xlsx');res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.setHeader('Content-Disposition',`attachment; filename="Retina-Spectacle-${acc}.xlsx"`);return res.end(b)}job.result=JSON.parse(gunzipSync(await asset(base+'result.json.gz')))}return send(res,job);}
 return send(res,{detail:'Not found'},404);
 }catch(e){return send(res,{detail:e.message||'Service temporarily unavailable'},e.status>=400&&e.status<600?e.status:503)}};
